name: json_hive_generator
description: Add-on import/export feature for hive to json
homepage: https://github.com/pocket-red-fox
repository: https://github.com/pocket-red-fox/JSON-Hive-Generator
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
